fix: Fixed Maya exception on FBX import
ftrackhq/ftrack-connect-pipeline-definition pull request #16
Opened 2022-11-22 11:06 UTC by henriknorin-ftrack

Resolves : 

* CLICKUP-3gb0443

- [X] The PR contains update to the release notes.

This PR has been tested on :

- [ ] Windows.
- [X] MacOs.
- [ ] Linux.

## Changes

Fixed bug on FBX Camera import.

## Test

Publish FBX Camera, then attempt to load it in Maya. It should succeeed.

2022-11-28 08:20 UTC, lluisFtrack requested changes

2022-11-28 08:20 UTC, lluisFtrack commented on doc/release/release_notes.rst
> +        :tags: houdini
why tag = houdini?

2022-11-28 10:06 UTC, henriknorin-ftrack commented on doc/release/release_notes.rst
> +        :tags: houdini
Typo, fixing

2022-11-29 08:34 UTC, lluisFtrack approved these changes
LGTM

2022-11-29 09:35 UTC, merged